### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [grevelem/TC359Project8#1]
It looks like this code isn't quite passing the specs yet. You'll be able to run them without errors if you remove the trailing commas. For example, change [line 7 in `bootstrap_alert_spec.rb`](https://github.com/grevelem/TC359Project8/blob/master/spec/helpers/methods_practice_helpers/bootstrap_alert_spec.rb#L7) from:

``` ruby
describe '#bootstrap_alert', do
```

to:

``` ruby
describe '#bootstrap_alert' do
```

Once you make this change, you should be able to see these failures:

```
  1) MethodsPracticeHelpers#current_date_and_time returns the properly formatted date and time for February 14, 2015 at 7:27pm
     Failure/Error: expect(current_date_and_time).to eq('February 14, 2015 at 7:27pm')

       expected: "February 14, 2015 at 7:27pm"
            got: "February 14, 2015 at  7:27pm"

       (compared using ==)
     # ./spec/helpers/methods_practice_helpers/current_date_and_time_spec.rb:15:in `block (3 levels) in <top (required)>'

  2) MethodsPracticeHelpers#current_date_and_time returns the properly formatted date and time for May 6, 2008 at 1:56am
     Failure/Error: expect(current_date_and_time).to eq('May 6, 2008 at 1:56am')

       expected: "May 6, 2008 at 1:56am"
            got: "May 6, 2008 at  1:56am"

       (compared using ==)
     # ./spec/helpers/methods_practice_helpers/current_date_and_time_spec.rb:25:in `block (3 levels) in <top (required)>'
```

Let me know if you find yourself at a loss for how to fix this and I'll be happy to help further.

**Comment by grevelem** [comment]
Hey Professor Fritz, I've removed the trailing commas and pushed my changes to github. Is that the correct fix? Thanks!

**Comment by chrisvfritz** [comment]
That's _part_ of it. The spec errors now show up successfully, but the ideal would be when we run `bundle exec rspec` from your project directory, none of the examples fail. It looks like you still need to make a tweak to the `current_date_and_time` method pass these last two specs.

**Comment by grevelem** [comment]
Oh there we go! Finally got it to turn green. This look any better? Thanks!

**Comment by chrisvfritz** [comment]
:+1: Wonderful!

**Comment by grevelem** [comment]
awesome! Thanks Professor Fritz!
